### PR TITLE
nightly test: increase timeout 

### LINKED ISSUE #1071: staking-miner integration tests failed against latest polkadot build.
Go to [job logs](https://github.com/paritytech/polkadot-staking-miner/commit/118b1e3898a540b2b53dc73135894d7b42b3081c/checks/15405458399) to see details about the failure.

### PR DESCRIPTION
**Pull request by sigurpol**
- Increase the mining solution timeout from 20 to 40 minutes. During manual testing on CI, the entire process takes between 11-12min to 28-29 minutes at most, so we should allow for some buffer time.
- Adjust RUST_LOG levels for miner and zombienet processes

Close #1071

### CODE REVIEW

File: tests/multi_block_monitor.rs [hunk 1]
```diff
@@ -190,7 +193,10 @@ async fn run_zombienet() -> (KillChildOnDrop, u16) {
             .stdout(process::Stdio::piped())
             .stderr(process::Stdio::piped())
             .args(["--provider", "native", "-l", "text", "spawn", config_path])
-            .env("RUST_LOG", "error,runtime=error")
+            .env(
+                "RUST_LOG",
+                "runtime::multiblock-election=trace,runtime::staking=info",
```
Comment (kianenigma) [inline tests/multi_block_monitor.rs:198]: info is the default log level fwiw, so the last log level is a noop.

**Review by kianenigma — APPROVED** [review]
